org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
neo_version=26.3.0.51-beta
neo_version_range=[26.3,26.4)
loader_version_range=[4,)

mod_id=kaleidoscope_tavern
mod_name=Kaleidoscope Tavern
mod_license=BSD-3-Clause + CC BY-NC-SA 4.0
mod_version=1.1.2-neoforge+mc26.3
mod_group_id=com.github.ysbbbbbb
mod_authors=ysbbbbbb, tartaric_acid
mod_description=Focused on tavern-themed content, adding a complete brewing system along with a rich selection of decorative blocks to bring your tavern to life.